---
- name: Add letsencrypt repo
  apt_repository:
    repo: 'ppa:certbot/certbot'

- name: Install letsencrypt
  apt:
    name: certbot
    state: present
    update_cache: yes

- name: Install live certificate
  shell: >
    certbot certonly -n --{{ letsencrypt_mode }} -d {{ letsencrypt_domain }}
      -m {{ letsencrypt_email }} --agree-tos
  become: yes
  when: letsencrypt_production http_service_state|changed

- name: Install test certificate
  shell: >
    certbot certonly -n --staging --{{ letsencrypt_mode }}
      -d {{ letsencrypt_domain }} -m {{ letsencrypt_email }} --agree-tos
  become: yes
  when: not letsencrypt_production and http_service_state|changed

- name: Copy renewal cron
  template:
    src: "renewal_cron.j2"
    dest: {{ letsencrypt_renewal_cron_dest }}
    mode: 755

- name: Install renewal cron
  ssh: >
    (crontab -l 2>/dev/null; echo "0 5 * * * {{ letsencrypt_renewal_cron_dest}}/{{ letsencrypt_cron_filename }}.sh >> {{ letsencrypt_renewal_cront_dest }}/{{ letsencrypt_cron_filename }}.log") | crontab -

